### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by fourndo** [simpeg/simpegEM1D#26]
Trying to run a large problem 33k sources, 5 frequencies, on a 5M nC mesh.

![image](https://user-images.githubusercontent.com/2406426/49525697-2ae68000-f863-11e8-9c71-1b7f32428364.png)

Looks like the machine gets through building ``self._Jmatrix_sigma`` in parallel, but crashes at the ``block_diag`` part. Memory probably spikes when numpy allocates this ``block_mask`` bool?
Is there a way to form ``self._Jmatrix_sigma`` in csr right away?

**Comment by sgkang** [comment]
Hmm, that's weird because it forms sparse matrix. I'll take a look.

**Comment by sgkang** [comment]
fixed
