### ISSUE TITLE
EM1D - Error installing - Fortran Compiler

### ISSUE THREAD

**Issue by jc-barreto** [simpeg/simpegEM1D#28]
Hello again,

I'm trying to install simpeg EM 1D trough pip install simpegEM1D and I'm having a problem with Fortran compiler. I have silverfrost FTN95 and mingw-w64, should I have something else?

Cheers,

![image](https://user-images.githubusercontent.com/42352209/50284630-90389480-0451-11e9-9c87-bb00d8208a72.png)

![image](https://user-images.githubusercontent.com/42352209/50284634-9464b200-0451-11e9-91e3-9d5317ffd0eb.png)

![image](https://user-images.githubusercontent.com/42352209/50284642-97f83900-0451-11e9-9266-f8b231df3401.png)

**Comment by lheagy** [comment]
Hi @jc-barreto: I transferred your issue over to the SimPEG EM1D repository. @sgkang: would you be able to help @jc-barreto with the installation?

**Comment by fourndo** [comment]
@jc-barreto : I had a similar issue here and fixed it with the following sequence:
1- Install [tdm64-gcc-5.1.0](http://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/tdm64-gcc-5.1.0-2.exe/download) 

2- [Download and unzip the fortran compiler](http://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%205%20series/5.1.0-tdm64-1/gcc-5.1.0-tdm64-1-fortran.zip/download) (overwrite) in the ```C:\TDM-GCC-64``` directory

3- Add the ```C:\TDM-GCC-64\bin``` to your PATH environment

4- In a command terminal ```activate simpegEM1D``` and run ```conda uninstall mingw```, this makes sure that the install goes through the TDM-GCC-64 compiler.

5- Re-run the install

Since you have other compilers, you might also need to temporarily remove them from your path.

**Comment by lheagy** [comment]
Thanks @fourndo: is there a place we can add this to the docs?

**Comment by fourndo** [comment]
Well I have to update the [GIFtoolsCookbook Intallation] page for sure (https://giftoolscookbook.readthedocs.io/en/latest/content/installation.html#python-installation-optional), but simpeg should probably have the same under some ```Windows``` users type of thing.

@jc-barreto : Can you confirm it works on your side too before we proceed? Worked on three different machines on my side... but who knows.

**Comment by fourndo** [comment]
@jc-barreto Yes I figured that the activate wouldn't work in your case since your are installing simpegEM1D directly in your base environment. My bad.

Can you still try to run:
```conda uninstall mingw```

**Comment by jc-barreto** [comment]
I had done before, so now gives the msg: PackagesNotFoundError : The
following packages are missing from the target environment:
  - mingw

Running the install again, I have this msg now: fatal error C1083: Cannot
open include file: 'io.h': No such file or directory






<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sem
vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

dom <notifications@github.com> escreveu no dia sexta, 21/12/2018 à(s) 17:20:

**Comment by fourndo** [comment]
Can you post the whole log?

**Comment by jc-barreto** [comment]
I had sent in a pdf, in attached

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sem
vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

dom <notifications@github.com> escreveu no dia sexta, 21/12/2018 à(s) 17:39:

**Comment by fourndo** [comment]
Sorry can't download this somehow, only see advertisement for AVG. 
Screen grab?

**Comment by jc-barreto** [comment]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]




<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sem
vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

dom <notifications@github.com> escreveu no dia sexta, 21/12/2018 à(s) 17:44:

**Comment by fourndo** [comment]
Yikes, still can see anything. Is it just me?

**Comment by fourndo** [comment]
According to [this thread](https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory) it is a Visual Studio issue.
What do you currently have for VS?

**Comment by fourndo** [comment]
I have [Visual Studio Community](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2017) with this installed

![image](https://user-images.githubusercontent.com/2406426/50357730-dd793c80-050b-11e9-926c-5276c08eb3d1.png)

**Comment by fourndo** [comment]
@jc-barreto Did you manage to get it going?

Found out that by installing TDM-GCC with the ```All packages```, I could skip the Fortran patch

![install_mingw_2](https://user-images.githubusercontent.com/2406426/50617254-0c46c980-0ea1-11e9-8a10-03ed804c3a70.png)

**Comment by jc-barreto** [comment]
Hi! @fourndo 
sorry for the late reply. I have installed again the visual studio, but  I still with the error
![image](https://user-images.githubusercontent.com/42352209/50636920-d7458000-0f4f-11e9-8062-2bbb2859fe9a.png)

I also removed the TDM-GCC and installed again with all packages, but the error is the same...

![image](https://user-images.githubusercontent.com/42352209/50636987-0f4cc300-0f50-11e9-98e0-6099e581eb4f.png)

**Comment by sgkang** [comment]
Hi @jc-barreto, 

Is this still issue for you?
(I got a new window machine, and followed what dom suggested, and it seems working fine)

Let us know if this still an issue for you.

**Comment by jc-barreto** [comment]
Hello @sgkang , I couldn't install on my computer, It was giving the error above, but then I installed at another computer and it worked. So, I think is something on my computer...
