### ISSUE TITLE
Forward with VTEM waveform

### ISSUE THREAD

**Issue by jc-barreto** [simpeg/simpegEM1D#47]
Hello,

I'm trying to compare SimPEG with SimpegEM1D reproducing the  [Bookpurnong](https://www.youtube.com/watch?v=hcGjlOhf0ig&t=350s) example
but the predicted data is quite different. Shouldn't be similar in order-of-magnitude?

![image](https://user-images.githubusercontent.com/42352209/95333945-58f4db00-08a5-11eb-9c66-5ec593fb0a74.png)
![image](https://user-images.githubusercontent.com/42352209/95334166-ad985600-08a5-11eb-8bda-202f93119c25.png)

![image](https://user-images.githubusercontent.com/42352209/95332548-7f197b80-08a3-11eb-9092-fc49a1ffef54.png)
![image](https://user-images.githubusercontent.com/42352209/95332614-99ebf000-08a3-11eb-98d4-1db0e2005c3a.png)
![image](https://user-images.githubusercontent.com/42352209/95332741-bf78f980-08a3-11eb-8db4-b2c682bee560.png)
![image](https://user-images.githubusercontent.com/42352209/95332804-d3246000-08a3-11eb-9825-fdf6dadb812c.png)

`
```
from simpegEM1D import *


from SimPEG import *
import numpy as np


import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt


dobs = np.load('data_book.npy')

time_channels = np.vstack([
    [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    [470e-7, 598e-7, 726e-7, 886e-7, 1118e-7, 1454e-7, 1852e-7, 2344e-7, 2952e-7, 3706e-7, 4644e-7, 5814e-7, 7278e-7, 9112e-7, 11170e-7, 14292e-7, 17912e-7, 22460e-7, 28174e-7, 35356e-7, 44388e-7, 55750e-7, 7.00e-03, 8.80e-03]
]).T


waveform = np.vstack([
    np.r_[-10, -9.29, -8.41, -7.26, -5.28, -3.62, -2.33, -0.62, 0.00, 0.0266, 0.0276, 0.0286, 10.000]*1e-3,
    np.r_[0, 20, 40, 60, 80, 90, 95, 99, 100, 1.53, 0.566, 0.000, 0.000]/100.
]).T


t0 = -1*waveform[0, 0]
offTime=t0+29e-6
a =3

time_input_currents = waveform[:, 0]+t0

input_currents = Waveform.VTEMFun(time_input_currents,t0,offTime,a)

times = time_channels[:-3, 1] + t0


fig, ax = plt.subplots(1, 1)
ax.plot(time_input_currents,input_currents,label='VTEMfun')
ax.plot(time_input_currents,waveform[:, 1], 'o', label='Points')
ax.set_xlabel("time (s)")
ax.set_ylabel("Normalized current")
ax.grid("k", alpha=0.5)
plt.legend()


area = 313.98
radius = np.sqrt(area/np.pi)
system_height = 39.8
rxloc = np.array([0, 0., 100+system_height], dtype=float)
srcloc = np.array([0., 0., 100+system_height], dtype=float)


# cs,csz, ncx, ncz, npad = 5.0,1.0, 25, 31,17
# hz = [ (csz, ncz), (cs, npad, 1.3)]
hz = get_vertical_discretization_time(times, facter_tmax=0.5, factor_tmin=10.)
mesh1D = set_mesh_1d(hz)
depth = -mesh1D.gridN[:-1]
LocSigz = -mesh1D.gridCC




TDsurvey = EM1DSurveyTD(
    rx_location = rxloc,
    src_location = srcloc,
    topo = np.r_[0.,0.,100.],
    depth = depth,
    rx_type = 'dBzdt',
    wave_type = 'general',
    src_type = 'CircularLoop',
    a = radius,
    time = times,
    input_currents = input_currents,
    time_input_currents = time_input_currents,
    base_frequency=25,
    n_pulse=1
    )

sig_half = 1e-1
chi_half =0.
expmap = Maps.ExpMap(mesh1D)

sig = np.ones(TDsurvey.n_layer)*sig_half
mtrue = np.log(sig)

fig, ax = plt.subplots(1,1, figsize=(5, 8))
ax.plot(sig,depth)
ax.grid(which = 'major', linestyle='-', linewidth=0.2)

fig, ax = plt.subplots(1,1, figsize=(5, 8))
Utils1D.plotLayer(sig, mesh1D, showlayers=True)
#ax.set_ylim(-100,0)

get_ipython().run_cell_magic('time', '', 'prob = EM1D(mesh1D, sigmaMap=expmap, verbose=False)\nif prob.ispaired:\n    prob.unpair()\nif TDsurvey.ispaired:\n    TDsurvey.unpair()\nprob.pair(TDsurvey)\nprob.chi = np.zeros(TDsurvey.n_layer)\nd_true = TDsurvey.dpred(mtrue)')


std = 0.05
floor = 1e-12
dobs = dobs[:-3]  
uncert = abs(dobs) * std + floor



dpred_3d= np.load('dpred_book_3D.npy')



fig, ax = plt.subplots(1, 1,figsize=(8,6))

ax.loglog(time_channels[:-3, 1], dobs, "C0s", label="dobs")
plt.errorbar(time_channels[:-3, 1], dobs, yerr=uncert, color="C0")
ax.loglog(time_channels[:-3, 1], -d_true, "C1", label="dpred_1D")
ax.loglog(time_channels[:-3, 1], -dpred_3d, "C2", label="dpred_3D")
ax.grid('k', alpha=0.5)
ax.legend()
```

`

**Comment by sgkang** [comment]
@jc-barreto I'll take a look today.

**Comment by sgkang** [comment]
Sorry for being too late. Hope you figured this out. 
If not there were few things that you misunderstood: 

1D code is structured differently from 3D code, specifically for the waveform 

1. You can directly input your waveform, so no need to use any additional function. 
Below is what I did using your script:

```python
time_input_currents = waveform[:-1, 0]
input_currents = waveform[:-1, 1]
times = time_channels[:-3, 1]
```

2. The `input_currents`  must end with zero value, i.e. the end of the waveform is zero. 
And, I assume that as `t0`. So, similarly, when setting `times`, you don't have to add `t0`. 

With that fixes, you get:

![image](https://user-images.githubusercontent.com/6054371/96192891-d64eca00-0efb-11eb-82cf-4441b3e67c22.png)

It should be comparable with 3D code. 
Let me know if you still have this problem.

**Comment by jc-barreto** [comment]
Thank you @sgkang for the answer.
So in SimPEG the waveform has to begin in zero and can finish at any time.
And in SimpegEM1D the waveform has to finish in zero, and can begin at any time? even negative time?
With this information, I run SimPEG [here](https://github.com/jc-barreto/SimPEG_Tests_Jenny/blob/main/TDEM_inversion_bookpurnong.ipynb) and compared with SimpegEM1D [here](https://github.com/jc-barreto/SimPEG_Tests_Jenny/blob/main/SimPEGEM1D%20VTEM%20data%20book.ipynb) and still with 2 orders of magnitude of difference.

![image](https://user-images.githubusercontent.com/42352209/96580015-9444d000-12cf-11eb-9269-29d348c0654b.png)

**Comment by sgkang** [comment]
@jc-barreto : that seems the normalization issue. Try to divide the response with the source loop area, and see if 1D and 3D responses are matching. 3D response seems normalized by the source loop area.
